language: node.js
services:
  - docker

before install:
  - docker build -t gunavathiduraisamy/reactapp -f Dockerfile.dev .

scripts:
  - docker run gunavathiduraisamy/reactapp npm run test -- --coverage
